CREATE TABLE IF NOT EXISTS public.player_statistics (
    player_id UUID PRIMARY KEY REFERENCES public.players(id) ON DELETE CASCADE,

    battles_total BIGINT NOT NULL DEFAULT 0,
    battles_won BIGINT NOT NULL DEFAULT 0,
    battles_lost BIGINT NOT NULL DEFAULT 0,
    current_win_streak INTEGER NOT NULL DEFAULT 0,
    best_win_streak INTEGER NOT NULL DEFAULT 0,
    current_lose_streak INTEGER NOT NULL DEFAULT 0,
    best_lose_streak INTEGER NOT NULL DEFAULT 0,

    expeditions_completed BIGINT NOT NULL DEFAULT 0,
    expedition_wins BIGINT NOT NULL DEFAULT 0,
    expedition_losses BIGINT NOT NULL DEFAULT 0,
    mobs_killed BIGINT NOT NULL DEFAULT 0,
    bosses_killed BIGINT NOT NULL DEFAULT 0,
    hidden_mobs_killed BIGINT NOT NULL DEFAULT 0,
    difficulty_1_kills BIGINT NOT NULL DEFAULT 0,
    difficulty_2_kills BIGINT NOT NULL DEFAULT 0,
    difficulty_3_kills BIGINT NOT NULL DEFAULT 0,
    bestiary_discovered BIGINT NOT NULL DEFAULT 0,

    pvp_attacks_done BIGINT NOT NULL DEFAULT 0,
    pvp_attacks_received BIGINT NOT NULL DEFAULT 0,
    pvp_wins_attacking BIGINT NOT NULL DEFAULT 0,
    pvp_losses_attacking BIGINT NOT NULL DEFAULT 0,
    pvp_wins_defending BIGINT NOT NULL DEFAULT 0,
    pvp_losses_defending BIGINT NOT NULL DEFAULT 0,
    revenge_wins BIGINT NOT NULL DEFAULT 0,
    revenge_losses BIGINT NOT NULL DEFAULT 0,

    copper_earned_total BIGINT NOT NULL DEFAULT 0,
    silver_earned_total BIGINT NOT NULL DEFAULT 0,
    gold_earned_total BIGINT NOT NULL DEFAULT 0,
    onix_earned_total BIGINT NOT NULL DEFAULT 0,
    copper_spent_total BIGINT NOT NULL DEFAULT 0,
    silver_spent_total BIGINT NOT NULL DEFAULT 0,
    gold_spent_total BIGINT NOT NULL DEFAULT 0,
    onix_spent_total BIGINT NOT NULL DEFAULT 0,
    copper_stolen_total BIGINT NOT NULL DEFAULT 0,
    silver_stolen_total BIGINT NOT NULL DEFAULT 0,
    gold_stolen_total BIGINT NOT NULL DEFAULT 0,
    copper_lost_total BIGINT NOT NULL DEFAULT 0,
    silver_lost_total BIGINT NOT NULL DEFAULT 0,
    gold_lost_total BIGINT NOT NULL DEFAULT 0,
    biggest_robbery_copper_value BIGINT NOT NULL DEFAULT 0,
    biggest_loss_copper_value BIGINT NOT NULL DEFAULT 0,

    copper_deposited_total BIGINT NOT NULL DEFAULT 0,
    silver_deposited_total BIGINT NOT NULL DEFAULT 0,
    gold_deposited_total BIGINT NOT NULL DEFAULT 0,
    copper_withdrawn_total BIGINT NOT NULL DEFAULT 0,
    silver_withdrawn_total BIGINT NOT NULL DEFAULT 0,
    gold_withdrawn_total BIGINT NOT NULL DEFAULT 0,

    inventory_items_count BIGINT NOT NULL DEFAULT 0,
    equipped_items_count BIGINT NOT NULL DEFAULT 0,
    inventory_total_value_copper BIGINT NOT NULL DEFAULT 0,
    equipped_total_value_copper BIGINT NOT NULL DEFAULT 0,
    account_estimated_value_copper BIGINT NOT NULL DEFAULT 0,
    most_valuable_item_id BIGINT,
    most_valuable_item_name TEXT,
    most_valuable_item_value_copper BIGINT NOT NULL DEFAULT 0,

    achievements_completed BIGINT NOT NULL DEFAULT 0,
    achievement_phases_completed BIGINT NOT NULL DEFAULT 0,
    achievement_points_total BIGINT NOT NULL DEFAULT 0,
    achievement_rewards_claimed BIGINT NOT NULL DEFAULT 0,
    secret_achievements_discovered BIGINT NOT NULL DEFAULT 0,

    quests_completed BIGINT NOT NULL DEFAULT 0,
    daily_quests_completed BIGINT NOT NULL DEFAULT 0,
    weekly_quests_completed BIGINT NOT NULL DEFAULT 0,

    grimoire_powers_equipped BIGINT NOT NULL DEFAULT 0,
    grimoire_powers_upgraded BIGINT NOT NULL DEFAULT 0,
    pets_unlocked BIGINT NOT NULL DEFAULT 0,
    pets_fed_total BIGINT NOT NULL DEFAULT 0,
    recipes_learned_total BIGINT NOT NULL DEFAULT 0,
    profession_actions_total BIGINT NOT NULL DEFAULT 0,

    last_battle_at TIMESTAMPTZ,
    last_win_at TIMESTAMPTZ,
    last_loss_at TIMESTAMPTZ,
    last_boss_kill_at TIMESTAMPTZ,
    last_hidden_kill_at TIMESTAMPTZ,
    last_quest_completed_at TIMESTAMPTZ,
    last_achievement_claimed_at TIMESTAMPTZ,

    extra JSONB NOT NULL DEFAULT '{}'::jsonb
);
