ALTER TABLE IF EXISTS public.achievement_definitions
    ADD COLUMN IF NOT EXISTS season_code VARCHAR(20) NOT NULL DEFAULT 'S01',
    ADD COLUMN IF NOT EXISTS phase INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS is_seasonal BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
